### ISSUE TITLE
Exportação para o educacenso

### ISSUE THREAD

**Issue by lucasdavila** [ieducativa/ieducar#7]
Implementar no iEducar integração com o educacenso.

**Comment by Ertonilson** [comment]
O layout de migração você encontra no site oficial do Educacenso:
http://download.inep.gov.br/educacao_basica/educacenso/migracao/2014/layout_de_migracao_2014.pdf

**Comment by lucasdavila** [comment]
Oi @Ertonilson, obrigado pela dica.

A Portabilis está implementando isto atualmente, estou fechando esta issue por este motivo.
